brandName: Mama Fern
tagline: Rooted in the Everyday
baseUrl: https://mamafern.com
twitterHandle: '@mamafern'
defaultOgImage: /og-image.png
defaultDescription: >-
  Rooted in the Everyday, our organic cotton apparel is here to let every part
  of the family shine.
defaultKeywords:
  - mama fern
  - family apparel
  - crunchy mom clothing
  - natural fabric kids clothes
  - earthy family fashion
  - grounded family clothing
  - boho family apparel
  - cottagecore kids clothing
  - matching family outfits
  - organic family clothing
  - low tox clothing
  - sustainable clothing
  - sustainability
